USE [master]
GO
/****** Object:  Database [ScheduleDB]    Script Date: 2017-08-06 5:07:03 PM ******/
CREATE DATABASE [ScheduleDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ScheduleDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ScheduleDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ScheduleDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ScheduleDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ScheduleDB] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ScheduleDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ScheduleDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ScheduleDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ScheduleDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ScheduleDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ScheduleDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ScheduleDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ScheduleDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ScheduleDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ScheduleDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ScheduleDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ScheduleDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ScheduleDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ScheduleDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ScheduleDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ScheduleDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ScheduleDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ScheduleDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ScheduleDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ScheduleDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ScheduleDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ScheduleDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ScheduleDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ScheduleDB] SET RECOVERY FULL 
GO
ALTER DATABASE [ScheduleDB] SET  MULTI_USER 
GO
ALTER DATABASE [ScheduleDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ScheduleDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ScheduleDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ScheduleDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [ScheduleDB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [ScheduleDB]
GO
/****** Object:  Table [dbo].[Schedule]    Script Date: 2017-08-06 5:07:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Schedule](
	[StudentID] [int] NOT NULL,
	[SectionID] [int] NOT NULL,
 CONSTRAINT [PK_Schedule] PRIMARY KEY CLUSTERED 
(
	[StudentID] ASC,
	[SectionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Sections]    Script Date: 2017-08-06 5:07:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sections](
	[SectionID] [int] NOT NULL,
	[CourseName] [nvarchar](50) NOT NULL,
	[Professor] [nvarchar](100) NULL,
	[CourseTimes] [nvarchar](100) NOT NULL,
	[Description] [nvarchar](250) NULL,
 CONSTRAINT [PK_Sections] PRIMARY KEY CLUSTERED 
(
	[SectionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Students]    Script Date: 2017-08-06 5:07:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Students](
	[StudentID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[Program] [nvarchar](50) NOT NULL,
	[Restrictions] [nvarchar](150) NULL,
 CONSTRAINT [PK_Students] PRIMARY KEY CLUSTERED 
(
	[StudentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Schedule]  WITH CHECK ADD  CONSTRAINT [FK_Schedule_Sections] FOREIGN KEY([SectionID])
REFERENCES [dbo].[Sections] ([SectionID])
GO
ALTER TABLE [dbo].[Schedule] CHECK CONSTRAINT [FK_Schedule_Sections]
GO
ALTER TABLE [dbo].[Schedule]  WITH CHECK ADD  CONSTRAINT [FK_Schedule_Students] FOREIGN KEY([StudentID])
REFERENCES [dbo].[Students] ([StudentID])
GO
ALTER TABLE [dbo].[Schedule] CHECK CONSTRAINT [FK_Schedule_Students]
GO
USE [master]
GO
ALTER DATABASE [ScheduleDB] SET  READ_WRITE 
GO
